### PR TITLE
Simple Fix

### PR DESCRIPTION
**Pull request by cbo317110**
- Fix link to Github, Twitter and Gitlab at speakers page
- Add a lock file to .gitignore to allow npm usage

### CODE REVIEW

**Comment by Halfeld** [comment]
Hey brother! thanks for the PR, but the `dist` directory doesn't need to be versioned because we're using [netlify
[netlify] (https://www.netlify.com/) as a CD instead of the Github pages, so this directory doesn't have to be in the repository.
The `package-lock` needs be versioned, 'cause it work like `yarn.lock` by yarn or `Gemfile.lock` by the ruby bundler, It was created for us to no longer use [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) in production enviromment.
About modifying links, can you add the `v-if` directive too? because people who do not have social media, the icons will appear there too

**Comment by cbo317110** [comment]
Already has the v-if directive i simple added the url before the value.
I will fix these things, `package-lock` is created on every `npm install` no?
btw, soon i up these fixes.
Thanks

**Comment by Halfeld** [comment]
Oh, sorry, I didn't see it hehe...

The `package-lock` is created yes, but the lock as the name speaks is to block the versions of the packages, if you don't versioned, it loses the sense of having entered as a feature in npm

**Comment by cbo317110** [comment]
Done.

**Comment by Halfeld** [comment]
Merged! Tamo together! <3

**Pull request merged**
